## 01创建数组

In [1]:
import numpy as np

In [2]:
# 1、numpy.array()
a = np.array([1,2,3,4])
b = np.array([1.2,2,'3'])
print(a,b) 
# numpy的数组类型要一直，列表可以是任何元素的类型，数组类型不一致回转换成一致的
# 数组打印出来中间没有逗号，列表有逗号
# help(np.array)

[1 2 3 4] ['1.2' '2' '3']


In [3]:
# 2、 numpy.arange()
a = np.arange(0,10,1)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
# 3、numpy.random
a = np.random.random((2,3)) # 形状(2,3) 范围0-1的随机数组
b = np.random.randint(0,10,(2,3)) #0-10的整形
c = np.random.uniform(0, 10, (2, 3))  # 生成0-10范围内的浮点型随机数，形状为(2, 3)
print(a, "\n", b,"\n",c)

[[0.61077466 0.96250243 0.69282199]
 [0.8736481  0.82624376 0.9156704 ]] 
 [[0 7 2]
 [2 5 8]] 
 [[4.92886114 4.56580863 4.29457571]
 [8.74784482 9.23923543 6.67620429]]


In [5]:
# 4、使用函数生成特殊的数组
a = np.zeros((2,2)) # 所有元素都是0
b = np.ones((3,2)) # 所有元素都是1
c = np.full((2,2),3) # 所有元素都是3
d = np.eye(3) # 对角线元素都是1，其他元素都是0
a,b,c,d

(array([[0., 0.],
        [0., 0.]]),
 array([[1., 1.],
        [1., 1.],
        [1., 1.]]),
 array([[3, 3],
        [3, 3]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))