## 03多维数组

In [36]:
import numpy as np

In [37]:
# ndim是维度数
a1 = np.array([1,2,3])
print(a1.ndim)
a2 = np.array([[1,2,3],[4,5,6]])
print(a2.ndim)
a3 = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])
print(a3.ndim)

1
2
3


In [38]:
# shape可以看出形状
print(a1.shape)
print(a2.shape)
print(a3.shape)

(3,)
(2, 3)
(2, 2, 3)


In [39]:
# reshape数组变形
a4 = a3.reshape((2,6))
print(a4)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [40]:
# 变一维
a5 = a3.reshape(1,12)  # 此时是二维
print(a5)
a6 = a3.reshape((12,)) # 此时是一维，有几个数字就是几维
print(a3.flatten())  # 直接展平一维

[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [41]:
# size可以获取元素的个数  此时没有括号
count = a3.size
print(count)

12


### 总结
ndarray.nidm()      可以看出数组的维度   
ndarray.shape       可以看出数组的形状    
ndarray.reshape(元组)转变数组形状，元组有几个数字就是几维    
ndarray.size 得到数组中的元素个数    
ndarray.flatten     转换成一维    