## 05索引和切片

In [31]:
import numpy as np

In [32]:
# 1、一维数组的切片和索引
a1 = np.arange(10)
# 索引操作
print(a1[4])
# 切片
print(a1[4:6])
# 使用步长
print(a1[:-1:2]) # 或者a1[::2]
# 使用负数
print(a1[-1])
# 操作和列表类似

4
[4 5]
[0 2 4 6 8]
9


In [33]:
# 2、多维数组
# 也是用中括号，用逗号分隔，逗号前面是行。后面是列
# 如果只有一个值，那就是行
a2 = np.random.randint(0,10,size=(4,6))
print(a2)

[[0 2 9 1 7 9]
 [7 7 7 6 3 9]
 [2 7 9 8 0 2]
 [9 0 9 1 2 5]]


In [34]:
# 获取某一行
print(a2[0]) # 第0行
print(a2[1:3])# 连续行
print(a2[[0,2,3]]) # 获取第0,2,3行

[0 2 9 1 7 9]
[[7 7 7 6 3 9]
 [2 7 9 8 0 2]]
[[0 2 9 1 7 9]
 [2 7 9 8 0 2]
 [9 0 9 1 2 5]]


In [35]:
# 具体数值
print(a2[1,2]) # 第一行，第二列
print(a2[[1,2],[1,3]]) # 第一行第一列和第2行第三列

7
[7 8]


In [36]:
# 连续的，第一行，第二行，第四列，第五列
print(a2[1:3,4:6])

[[3 9]
 [0 2]]


In [37]:
# 获取某一列的数据
print(a2[:,1:3])

[[2 9]
 [7 7]
 [7 9]
 [0 9]]


#

### 总结
1. 如果是数组是一维的，那么索引和切片跟python一样的
2. 如果数组的多维的(二维为例)，那么在中括号中给两个值，用逗号分隔，前面是行，后面是列，如果只有一个值，那代表的就是行
3. 如果是多维数组(二维为例),行的部分和列的部分，都是遵循一维数组的方式，可以使用整形，切片，还可以用中括号的性质来代表不连续的比如a[[1,2],[3,4]],那么返回(1,3),(2,4)

#### 布尔索引

In [39]:
a2 = np.arange(24).reshape(4,6)
print(a2)
print(a2<10)
print(a2[a2<10])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ True  True  True  True  True  True]
 [ True  True  True  True False False]
 [False False False False False False]
 [False False False False False False]]
[0 1 2 3 4 5 6 7 8 9]


### 数组值的替换

In [40]:
a3 = np.random.randint(0,10,size=(3,5))
print(a3)

[[9 1 0 0 0]
 [2 2 9 9 8]
 [8 5 7 8 1]]


In [42]:
a3[1] = 0 #  第一行都变成0
print(a3)

[[9 1 0 0 0]
 [0 0 0 0 0]
 [8 5 7 8 1]]


In [44]:
# 布尔索引替换
a3[a3<5] = 1
print(a3)

[[9 1 1 1 1]
 [1 1 1 1 1]
 [8 5 7 8 1]]


In [ ]:
# 函数替换
res = np.where(a3<5,0,1) # 不改变值
print(res)
print(a3)

[[1 0 0 0 0]
 [0 0 0 0 0]
 [1 1 1 1 0]]
[[9 1 1 1 1]
 [1 1 1 1 1]
 [8 5 7 8 1]]
