## 05数组的广播机制

In [1]:
import numpy as np
a1 = np.random.randint(0,5,size = (3,5))
print(a1)

[[2 4 0 1 3]
 [2 1 2 3 4]
 [1 4 1 3 3]]


In [2]:
# 数组和数之间的运算
print(a1*2)


[[4 8 0 2 6]
 [4 2 4 6 8]
 [2 8 2 6 6]]


In [3]:
# 数组和数组运算
a2 = np.random.randint(0,5,size = (3,5))
print(a2)

[[0 4 1 4 3]
 [3 3 0 3 1]
 [1 3 2 2 0]]


In [4]:
print(a1+a2)

[[2 8 1 5 6]
 [5 4 2 6 5]
 [2 7 3 5 3]]


In [15]:
# 形状不一致会报错
a3 = np.random.randint(0,5,size = (3,5))
print(a2*a3)  # 位置相同的元素相乘


[[ 0  4  4 12 12]
 [ 6  6  0 12  3]
 [ 0  9  0  0  0]]


In [ ]:
# 行数一样，列数不一样,但是有一个是1,可以进行运算(3,1)和(1,2)也可以
a4 = np.random.randint(0,5,size=(3,1)) 
print(a4)
print('*'*20)
print(a2)
print('*'*20)
print(a4+a2)
# 对后面的用1的那部分数据进行填充

[[2]
 [2]
 [2]]
********************
[[0 4 1 4 3]
 [3 3 0 3 1]
 [1 3 2 2 0]]
********************
[[2 6 3 6 5]
 [5 5 2 5 3]
 [3 5 4 4 2]]
