In [24]:
import numpy as np

In [25]:
a1 = np.random.randint(0,11,size=(3,4))
print(a1)

[[1 3 6 0]
 [8 8 4 7]
 [1 6 1 5]]


In [26]:
a1.resize(4,3) # 改变原数组
print(a1)

[[1 3 6]
 [0 8 8]
 [4 7 1]
 [6 1 5]]


In [27]:
# 数组切割
a2 = np.random.randint(0,5,size=(3,4))
a3 = np.hsplit(a2,2)
print(a3) # 平局分隔成两个数组


[array([[2, 1],
       [4, 2],
       [2, 4]]), array([[3, 1],
       [0, 1],
       [3, 1]])]


In [28]:
np.hsplit(a2,(1,2)) # vsplit是按照行进行切割

[array([[2],
        [4],
        [2]]),
 array([[1],
        [2],
        [4]]),
 array([[3, 1],
        [0, 1],
        [3, 1]])]

In [29]:
# 转置操作
print(a2)
a2.T # 不会改变原本的
print(a2)

[[2 1 3 1]
 [4 2 0 1]
 [2 4 3 1]]
[[2 1 3 1]
 [4 2 0 1]
 [2 4 3 1]]


In [ ]:
a3 = a1.transpose()
print(a3) # 改变会影响原数组
a3[0]=100
print(a1)


[[100 100 100 100]
 [  3   8   7   1]
 [  6   8   1   5]]
[[100   3   6]
 [100   8   8]
 [100   7   1]
 [100   1   5]]
