In [22]:
import numpy as np
a = np.random.randint(0,27,size=(4,3,2))
print(a)

[[[17 16]
  [22 13]
  [ 6 15]]

 [[ 3 26]
  [ 8 10]
  [19 12]]

 [[14  3]
  [ 6 19]
  [25 14]]

 [[ 2 19]
  [11 13]
  [11 23]]]


在NumPy中，axis参数用于指定沿着哪个维度进行操作。对于你给的三维数组，它的形状是 (4, 3, 2)，也就是说，数据有4个二维数组，每个二维数组的形状是 (3, 2)。

axis=0：沿着第一个维度（即4个二维数组）进行操作。例如，沿axis=0进行求和，会对每列进行求和，结果是一个形状为 (3, 2) 的数组。   
axis=1：沿着第二个维度（每个二维数组的3行）进行操作。例如，沿axis=1进行求和，会对每行进行求和，结果是一个形状为 (4, 2) 的数组。   
axis=2：沿着第三个维度（每行的2个元素）进行操作。例如，沿axis=2进行求和，会对每行的两个元素进行求和，结果是一个形状为 (4, 3) 的数组。   

In [23]:
a.max(axis=0),a.max(axis=1),a.max(axis=2)

(array([[17, 26],
        [22, 19],
        [25, 23]]),
 array([[22, 16],
        [19, 26],
        [25, 19],
        [11, 23]]),
 array([[17, 22, 15],
        [26, 10, 19],
        [14, 19, 25],
        [19, 13, 23]]))