In [1]:
import numpy as np

In [3]:
# 三角函数
pi = np.pi
x = pi
print(np.sin(x))
print(np.cos(x))
print(np.tan(x))
print(np.arcsin(1))
print(np.arccos(1))
print(np.arctan(x))
print(np.hypot(3,4)) #求斜边
print(np.degrees(x)) # 弧度转换成 角度
print(np.rad2deg(x)) # 弧度转换成 角度
print(np.radians(180)) # 度转换成弧度
print(np.deg2rad(180)) # 度转换成弧度


1.2246467991473532e-16
-1.0
-1.2246467991473532e-16
1.5707963267948966
0.0
1.2626272556789115
5.0
180.0
180.0
3.141592653589793
3.141592653589793


In [10]:
# 数值修约
a = np.random.randn(5)
print(a)

[-0.09500287  0.47828506  0.62842591 -0.79631898 -1.03931967]


In [13]:
print(np.around(a)) #四舍五入，小数
print(np.round_(a)) # 四舍五入 小数
print(np.rint(a))     


[-0.  0.  1. -1. -1.]
[-0.  0.  1. -1. -1.]
[-0.  0.  1. -1. -1.]
