In [27]:
import numpy as np

空值包括两种，一种是NAN,一种是NAF   
1. NAN 不是一个数字，浮点型
2. NAF 无穷大，浮点型

In [28]:
data = np.random.randint(0,10,size=(3,5)) 
print(data)

[[5 5 2 6 5]
 [6 6 1 4 2]
 [5 6 1 4 9]]


In [29]:
data = data.astype(np.float64)
data[0][1] = np.NAN
print(data)

[[ 5. nan  2.  6.  5.]
 [ 6.  6.  1.  4.  2.]
 [ 5.  6.  1.  4.  9.]]


In [30]:
# NAN和NAN不相等
print(np.nan == np.nan)

False


处理

In [31]:
# 删除nan
data[1,2] = np.NAN
print(data)

[[ 5. nan  2.  6.  5.]
 [ 6.  6. nan  4.  2.]
 [ 5.  6.  1.  4.  9.]]


In [32]:
# 删除缺失值
data = data[~np.isnan(data)]# nan不相等，所以用这个函数
print(data) # 

[5. 2. 6. 5. 6. 6. 4. 2. 5. 6. 1. 4. 9.]


In [ ]:
data = np.random.random(size=(3,5)) 
data[[1,2],[0,1]] = np.NAN
# 删除行
print(data)
print('-'*60)
line = np.where(np.isnan(data))[0]# [0]是所有行
datal = np.delete(data,line,axis = 0)
print(datal)

[[0.93391054 0.82108325 0.05469921 0.64966623 0.41762978]
 [       nan 0.38084108 0.67861007 0.90642245 0.48502707]
 [0.58424768        nan 0.91562034 0.0937374  0.06404136]]
------------------------------------------------------------
(array([1, 2], dtype=int64), array([0, 1], dtype=int64))
[1 2]
[[0.93391054 0.82108325 0.05469921 0.64966623 0.41762978]]
