In [2]:
import numpy as np

In [ ]:
# numpy.random.seed 随机数种子其他的都一样
# 没设置根据时针戳

0.417022004702574

In [ ]:
# numpy.random.rand() 0-1随机数
np.random.rand(2,3) # 考科一指定形状


array([[7.20324493e-01, 1.14374817e-04, 3.02332573e-01],
       [1.46755891e-01, 9.23385948e-02, 1.86260211e-01]])

In [ ]:
# numpy.random.randn() # 符合标准正态分布的
np.random.randn(2,3)# 可以指定形状

array([[-1.10593508, -1.65451545, -2.3634686 ],
       [ 1.13534535, -1.01701414,  0.63736181]])

In [ ]:
# np.random.randint()

In [ ]:
# np.random.choice
a = np.arange(0,10)
np.random.choice(a,6) # 随机选择三个数，可以重复，超过数量

array([1, 0, 1, 8, 8, 3])

In [ ]:
# np.random.shuffle
np.random.shuffle(a)
print(a) # 没有返回值，直接打乱原数组

[7 2 0 4 1 5 3 6 8 9]
